export const  default_list =[
	// {
	// 	address: "Tel Aviv, Center District, Israel",
	// 	code: "LLBG",
	// 	code_ata: "LLBG",
	// 	coords_lat: "32.0055",
	// 	coords_long: "34.8854",
	// 	name: "Ben Gurion International Airport",
	// },
	// {
	// 	address: "Dubai, Dubai Emirate, UAE",
	// 	code: "OMDB",
	// 	code_ata: "OMDB",
	// 	coords_lat: "25.2532",
	// 	coords_long: "55.3657",
	// 	name: "Dubai International Airport",
	// },
	{
		address : "St Michael, AK, United States",
		code : "PAMK",
		code_ata:"SMK",
		coords_lat:"63.490101",
		coords_long:"-162.110001",
		hours_diff:"-8.00",
		id:"9210",
		location_distance:"2.336444751042958",
		name:"St Michael"
	},
	{
		address:"Miami, FL, United States",
		code:"KMIA",
		code_ata:"MIA",
		coords_lat:"25.793200",
		coords_long:"-80.290604",
		hours_diff:"-4.00",
		id:"6322",
		location_distance:"6.167446826850104",
		name:"Miami International Airport"
	},
	{
		address: "Van Nuys, CA, USA",
		code: "KVNY",
		code_ata: "KVNY",
		coords_lat: "34.2096",
		coords_long: "118.4896",
		name: "Van Nuys Airport",
	},{
		address: "Oakland, CA, USA",
		code: "KOAK",
		code_ata: "KOAK",
		coords_lat: "37.7126",
		coords_long: "122.2197",
		name: "Metropolitan Oakland International Airport",
	},{
		address: "Buffalo, NY, USA",
		code: "KBUF",
		code_ata: "KBUF",
		coords_lat: "42.9397",
		coords_long: "78.7295",
		name: "Buffalo Niagara International Airport",
	},{
		address: "Fort Lauderdale, FL, USA",
		code: "KFXE",
		code_ata: "KFXE",
		coords_lat: "26.2005",
		coords_long: "80.1714",
		name: "Fort Lauderdale Executive Airport",
	},
	// {
	// 	address: "London, England, United Kingdom",
	// 	code: "EGGW",
	// 	code_ata: "EGGW",
	// 	coords_lat: "51.8763",
	// 	coords_long: "0.3717",
	// 	name: "EGGW",
	// },{
	// 	address: "Doha, Ad Dawhah Municipality, Qatar",
	// 	code: "OTBD",
	// 	code_ata: "OTBD",
	// 	coords_lat: "25.2609",
	// 	coords_long: "51.6138",
	// 	name: "Doha International Airport",
	// },{
	// 	address: "Riyadh, Riyadh, Saudi Arabia",
	// 	code: "OERK",
	// 	code_ata: "OERK",
	// 	coords_lat: "24.9636",
	// 	coords_long: "46.7007",
	// 	name: "King Khaled International Airport",
	// },
	{
		address: "Dallas, TX, USA",
		code: "KADS",
		code_ata: "KADS",
		coords_lat: "32.9700",
		coords_long: "96.8365",
		name: "Addison Airport",
	},
	// {
	// 	address: "Doha, Qatar",
	// 	code: "OTHH",
	// 	code_ata: "OTHH",
	// 	coords_lat: "25.2609",
	// 	coords_long: "51.6138",
	// 	name: "HAMAD INTERNATIONAL",
	// },
]